#!/usr/bin/env python
from sys import *
from os import *
from time import *
from datetime import *
format = "%Y-%m-%d %H:%M:%S"
for file_name in argv[1:]:
    mtime_file_name = '%s.swl.mtime' % file_name
    mtime_str = file(mtime_file_name).readline().strip()
    mtime = mktime(strptime(mtime_str[:19], format))
    utime(file_name, (mtime, mtime))
